CREATE TABLE bookmarks (
    id text PRIMARY KEY,
    owner_id text NOT NULL,
    revision bigint NOT NULL DEFAULT 1 CHECK (revision >= 1),
    url text NOT NULL,
    original_url text,
    title text NOT NULL DEFAULT '',
    description text,
    content_type text,
    source text,
    author text,
    language text,
    published_at timestamptz,
    last_visited_at timestamptz,
    favorite boolean NOT NULL DEFAULT false,
    pinned boolean NOT NULL DEFAULT false,
    read_state text NOT NULL DEFAULT 'unread' CHECK (read_state IN ('unread', 'reading', 'completed', 'archived')),
    reading_progress double precision CHECK (reading_progress IS NULL OR (reading_progress >= 0 AND reading_progress <= 1)),
    privacy_level text NOT NULL DEFAULT 'normal' CHECK (privacy_level IN ('normal', 'sensitive', 'private-vault', 'shared')),
    preview_image_ref text,
    extracted_text_ref text,
    offline_requested boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CHECK (length(id) > 0),
    CHECK (length(owner_id) > 0),
    CHECK (length(url) > 0)
);
